language: scala
jdk:
- openjdk8
script: make build
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
deploy:
  provider: script
  script: make travis-deploy
  skip_cleanup: true
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
