language: scala
services:
- docker
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
branches:
  only:
  - master
  - "/^v[\\d\\.]+$/"
script: make build
deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^v.*"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - SPARK_VERSION=2.4.5
  - HADOOP_VERSION=2.9.2
  - HIVE_VERSION=2.3.3
  - secure: jFbE3VSBYtLGiQHiDJQJjLoZiKGC/lWOUDf8E0xyxZh4D1b2VcowyGNIPpx/jo88v4C0olyxndhMYT8BfBdOjx46wzaddOugCHiUkCp+lBDf98iEEWulCakcZ4aF+TVY93v2Acljo3FQqTua+Cbrggf9WYgMt/nMXmG0bXsFcOzhWmx5Wv0q1OhuwVHASW74t0ZmfXcNemKDntP2W5QC8/lJotNa3YM4/B1DRNwpdOdaytFkMpQvn9OmLGNU5xxzvvs3dIzc+sPZJeE/3KWHC8a3oLO2NDOTLt3IzhUTcgk9MM3Btaz65FMW5i6bU9vzWmt5EMgbQ2HIhDos0zmKsELvIaDHvN1oByR49Mw1hdSjDdmt1x1m6FEpwJHv5BLyQB06/jITWM9EGUzMnEV6GGskzSmRvePMGSs0AftgT4LdYNe5Uc6JQGIx+eWXnAgRif2LkYCvUwhQIWitI37IwNF0NGcKibg7NMy0OIzCzgNTGzphfDq9nFUeGxZ429NpCuRP2f38AUz36ATXC/C0E79EQDXjPWt1LLpQVR1BZOcJnVDpkMVSfrKgEl/xk9HUIPj7F6Sg8RpMbP1912f4npQBU3q0oeSqXuqUoQ5yn35bmNrxzSIocRA0eIMidMmpfRxO8le0JwiIfMYGbioff+GJ9bl0uZaa7xxuBQEhe8s=
  - secure: TRDu/IMxlS79T9Y2NF4MOyZTTrLeHwQITIGwvp+NGtxebydcch/8ldsN8cvcJ1OfhjVsg1fRuBiBzWnADzKfhD6VKiIn1FMr9b1wW6zGsz0HjU6HccvuQNBBUXWBn7NJhFEN7vGldYtG9Z5frM9bsMy9okxnyCayvu/DDwvvIQbvEolA283SeMeEqB9QhStPvbR5+MFH6eMH01lX03tX4Q3NJ5YUgOFDflP9EISsTVclUrGPkmCsdks3tvjYwU61OpL48fQRK7HBBqv7xCSm94tJ4Sr5EELUmY+iNtyIqllACfN/msR1cZFjUyWjDEewOMd/6wy3wfRg9/bh5ZrLSnF2rWgTbI/I57DPcIF1rFuz+blVgSejRE50DNyMzKL//2IuGHw33Lx++yO73AoZvvjIeG8Jbz+4+6Elnc179Vgv0w4fRjU7SjudkEjz6nBDGbPBMgWZev7uCsF58J3cVX0oDHtFi8oLn2hQhh8BNqFZY3abnYq0HkAw72Sohy7CtNtcgFas2i3BnqJw7ueMvn8RaRQGME9XA+LcQsneg4ulqOtsf2mbsSiITXewxysXD6ucClYa3ZHnw3EuopTaf4qoEV5Y7WdCdFtSqxs+1Y/QHS9vATWomNpSdmkrw/pIN+J9vOt6JXd4hV1kZLIa/aFaeYq9AtMjnaTztrFVGNU=
  - secure: AyoBVtBg8kr8niqsyqZHW1fVACVCOFHx/qPV+bXXyQcQ5251ab0Xy02YyBnB5ls/l/xEdy/S/ROvYq1wySsdo+9ltN++wS2tBfmMHrM3kkC2pTN0kR43eo2Uj74Xl8Y4NgU8o9md9ZQmAvxttzBkaFZvBnPFgPmelrEfM3IeHfku3ZXvwPHCFzHOAbZeJhN6GvYfSPKWYrkh7y8lOSKdvdHoQhYBIUYwrmUU/mVuWbp4rDK8qJ3zKxFj2o+Ynhjtgz2eGPyPmXpz1jFJI7eTzD+/yp2ndMWnYtMjiyjxFuckTXV8BFaHpWMMWOmrbSD+SfZbGeOzDWETjqvSEUI0MmcTb7K588BbhZ/L07uHqMU134+9Dpu12SBNWzSoAHIpGcN84hJWbRVXF25BOZn6I7cNd/lED3DIiAnkWt8NvYwwWgXx4xxWKvdkYZwKKTFrkepKmgzbpDIprWokk7W6YrGQZX6Wzfnyyl6NaDVTLZiqRBMaZd8WNh+qjvEgVYyM2aKYYGEXkHrIbVh042WH3EAfHVnC4J3SsSvlq48Kvgq71/9LrwaFk5q3tiBEoZ3W7y2lPUZX2wfGaKHkfnf4OAvxWtt90Tctwn2PR9kp23UdulfItr7e0ddtTE7fAejqcADuCXjDeqvMc454qDxj8GVU+70Em7ZNaDu1WOVzXNU=
  - secure: bCwQLTh+9sFyg80izQXpIZdM/swTgGBYKQNmF3i2rJdnadBsuIPW8IJDX1Md4nCSRe8FpXsYcbUjvPQLPtYAogdafGgwN1hUdkL1kvyZsrQdlooKFGHN7HL8KzIy4vzRqPx0cpv9D31OmyvFS5PiiC7umOejt28URs3+QTjG40VObZXfRZWiHnzZuLsPlQbNloNCA1SB0TnHK5AY9AGmT1UAnTojeQgzuNHf5AeiSska/gmMKmJ081N35Bgd7gWe5WGiprjZDUa3muE59qOftu4/lTx0JXGzrLEB83QcrkZQ9e/Qr7ZndHDrQLekzqIse1QuNIGd3o/zaBHYVGfFRXnzOuDm6mKuobY6lcwJ/hzRBliNaf3ZkhJ8qataIwIXPmN/bkM2mmADNru2v0GBySRXdPkCPy6bddThADTFQZe4upr5BpNj0HZWGAa3uqSDyn/FHa09yI7Te6ORYoWiZdfakukJ+gyGJij0a6PIN3/jvdbEmlCoDaOspXA8P5hfBUnirpG5N0l9wt3sBeuMoXxRSQp/tKtlAil6wsg8U3w94I3cw+9b4bAXaziwg2Py/MoSnwK16nyjA3/jUt3AIpgYJ26KVr8q1RZDHJUg1eLuSG76oKusDf7+wPclynUIC+pmtAZaEuAHyqqjT8GRIAkZjN7qsR5ULQYK/tXExn8=
  - secure: dQntEPFWyLkww+jcSYEHrmRVIYSKMoVeXi57XPqYPNy7Bs/ubYnYApiRJp/mA/JpS0/hIrDepwalzGqDCMI1erIc0h0zDMXdZEZ0X5T3orQZtc1Lv5Kq6iIUwLc+3B8xd37S5y5tPUVwhHJS5gSTEgt81a/oYSwa9a9snLhnN/ZntqIrj+BHhuxQB0kJuw9XCBiRAreLh4VFXNQXAXL7xnvBPb+noJNVXP3YEilcbbnHsIcI5VYGBgC50y7g0k5xmWVMkcpsn4blGIjS2CIQI+FPtIDCTlsTyeqjE9HjSAGGa5O76yxgai3yNTW/26xo0SHqUvwRmkBmSNoIHV6/L3ZgDhK4HKNyep6JCYDZn0qFZXdX/IyW/O39cL1HFKZ0ygxJ9sysme+9jgyk7atKOAjM3HtxOZNgWTDw0mOesi48W7BY0VtN1KYmcM41sMDOMGytEszBlMPWPuiKxGd8Wo2d+bzFHvXYZQceurIp2dc/nCcHmXFFwzokbHB+haRkd/Slkavan/APj0P5cTvxwEGwAUpEIyXEuyMV7j/EZPB/erm7PbneeHVSB3nvQdgw46CqHVxOmc2NoJuoe2xMPhlBSiMU2DI94KU1bmLKZpe4zM52ygh1DxF7ak2Abo7QmRLM1s72NmulOwE1uYsdmy/e/nba0/RfiQbx4aLzAno=
before_install:
- openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in .travis/pubring.gpg.enc -out .travis/pubring.gpg
  -d
- openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in .travis/secring.gpg.enc -out .travis/secring.gpg
  -d
- chmod +x e2e/**/*.sh
