language: scala
services:
- docker
os: linux
dist: bionic
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
branches:
  only:
  - master
  - "/^v[\\d\\.]+$/"
before_install:
- openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in pubring.gpg.enc -out pubring.gpg
  -d
- openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in secring.gpg.enc -out secring.gpg
  -d
jobs:
  include:
  - stage: build
    script: ".travis/scripts/build.sh"
  - stage: test
    before_script: ".travis/scripts/docker.sh"
    script: ".travis/scripts/test.sh"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    deploy:
      provider: script
      script: ".travis/scripts/deploy.sh"
      skip_cleanup: true
      on:
        tags: true
env:
  global:
  - SPARK_VERSION=2.4.5
  - HADOOP_VERSION=2.9.2
  - HIVE_VERSION=2.3.3
  - GPP_DIR="`pwd`/.travis"
  - secure: nzSANbaWkGIkWceRR9HZ79NiIZHMd09477c31vq9rx5q/EN8q2o8lHBgrNhJ6RpToFPiGM2cKkoCaeABbbEEz4S037CG/JLVaFaaMIwgsxMOQifySWrHY1hzK++s4w58MFWoFf16Xsn6alOrtPc6kka/EeN/SCudkom2JW398q0W4izmRL2sM/TfDwHvHPqOuhXhhqzlwU3oXcOGzw6wIdDamFbYDq9664Qodvbsd6DUcqpwVlhDUA3X0oUSNmYcFOSRPPt1qDdXPmPajiGQ36+b763gsVyyhz/bNuUG76fdR1yrC9wYBYaj39hO+NjQS+/l+3NmBNsT0m0koZyTmv/WdteKGVOLoAqwN20Jtt7Zp/qluTJ56P+Ti6qaB/UPKf9HzlDH7tPoXAX1nqWgfrYi50a6gNxw4X4Xs1kI/llO48UTivJy5DHPGDXP0bsmwE2tbrygob2ylFRfdVfUJwOnzB9E4ifIUfkJPIw8FCfa59UmlcHrMQ2cH4gNz1opj5cEaDWdEeN5TZ54Vl2UNKV7TmoFvG5vyq9nwQR2eGeCrd1WcXd1TDLEWD0ei0jnXdCoS5vLwMRawTMYYNKLvrXgrMlEn0VwwY+8b4E6z6DJYXXzkn2luLU0jh/gAOlYQbSFyC3FyWwrS3MpP/DCQUW7z/s1KX7PY84G2C7InXY=
  - secure: T86344mWKCq2lRBi5Fol9e2HbJxz5Wqk+5tNjUyF8aWXRPBc2uUDx1CEvsbBqkIu8TCHwVW5G1GJsVn3gjDi5bZfEj5ckyB4MdBB+Pqo1lyGuVTqXMtfuJZYOI0wj2JVSoCTixBFQi87RdQ8ZMzkI2a/CpnkP6TvenOwnpLNJOIL8gaaz50LNLYFPg0ha01M5io6LEFxlgFmY3yyopJ6h9DQUb9DK7pz7GyA+S2BLvnoNFQWBd93HWZLFbqryrkZ7Lpj2bmuyNxfAjfXFFKcdkxSHVXGrcJs72xgnrPO6IpgBgkadiQqA8FcjuPHYaW3DRcCUrPvVNJ12CQ1Nb2ikl1RKYkafIM4A7+Ij4PgpuzM5Z/TPinzbkmw3bleFFBFAtla5BONKKZ3ClpH/3l+TebkB1bMMh5Pg5AV8ugsl3dtamNSoUomLYcZEDTCZ5mTS8fULESGjZ/0HZxUc+tJvkmLAgAT+phORt8qNAIfERxswzkMr39pvJ5fPk/rVdtxDTq7RfTnz70qqH6q+oX8qPvyuAPRGrmJ98ABnjLk6yxH+jInqTklKEmwT1MeXa6sgMiSK+3bRGvG3LQ8hfznukEBq5bvISrEy4ekPeH2ItdIqPTiYhqy4OecdJ3GMu496/FkSU4uIIYLYYmnjckHDU5+D0k0ZlSV2g9Rcs/KvtE=
  - secure: kYFRpuh2m3IxKuVJF7lwxTJi6FNJxdF1Hq9vuofTpS5Kb0QDCBqsB7qQVsfy39bUkD5rT5miw3u4NgY2g6dPR6ugoP3/T49YnLuucW4hF4VE8LQqeG5S+p8d9hio2oBnKdZwbnvFU3ZCun/n9jHXviSM3W6bF9/iYS3GxvUyELMVJJZyynJ1jSUHwmQYkLs4WnvxgEg2qqLBkIrEYiIKWrSLDGupmsRQXk3l650vDjsq7Ff5Cqh9wQ/9NgKci32YINOHv6xEm2ja3g6CywMCZ3ZwFqk7a21YMkgMJSiQO8ddQdM1WwWxBXqIyWoey2YggWiP1Jx+klyYxRrvrOigYPaEmw/iV8qvJfE9JHbj8RmvCnHloJu972b/35smzK1/dG+kgjWHvzrDh4dYkYPjCVx3rTbvvhis5VdLRlOyG9X+c7BJw+3LGbUT7ToWiRl1bD5jZv39nRA9gN4xnTlO4VwMTX2syhRXSs0Y6Wu2QbfU9w6pt4JVQpmayZBYwLtndmZu4ITByiRXA8sryIwRWx5xlErI6GoWv15JihWWfMRZRYAF/nJlRCVJDjP+3AhC36tmgUn7K0BozTjzkKimqf3IGd8FcbUBkdZkL540IwLssWw7RyhO9pN7SsmPphJTd0o67G36GAm7ZLKW/EUnIjB+2P4DSyHB9jh5powIuOE=
  - secure: VIBMcoM/TRgM+Lg792sz3Ct/gvMQOyFb0Xx0l4HW6k1XipopzTirXczg+OBdGGfjMneb2UNrTHbpdg97XsBnxCJWTHPvFFSPPRWlGO9z4jPQMkSFHaWaJas1WVlr297FJ9EqYPKVQrfu0KrR1ZgrzTJhMRojcukPGhR3nNMlgW7kTPS1dClgi0mziZM0DX/TVyjTtcMA1UaV+s+HRfXoYCX/8vMmqjZsqdQxZWy85JgIth7TLq4OGj3pyHLkAjQ7SUPupqdblOaVdZs+suLSdk1WaTM/TzmkSxZPQ/vVYw7RfYa7NneuBMMg3AI23SMDYPm5lfZ9HEPPQ2gcnOeWNlj0gNyQouTpDOuJNjveihDBIL35NwXUVOxzTzUhiyzM3NbWgSb6/PudG+25MuVf5fT0rgjUY/SQaXGiY2xh8dvtMBsLWiLykPz10GhkimEIeVppc5WejMDUdOgpS7UhMBRCpKqpK5SQUW/2AdSHq0FU3hGkSt7meJPiZDjmMKgVNbw5ipYtH7EEgCe394PrdwR/riOXfpU3tILmcHo3e9KQPjUkeX//Bj7B8I6Uv6ifmxu1xYLqzRavAg6P7cm5CToSKQRke0ck9H6AtTYazG2OyCDTkDbAqzYfi6w4AsSysLJQqzb3JVXdkO5v0yFKSO2ldEiaOtAhug5d9pF0GKY=
  - secure: Jn6BNDiSZoahzZ5nL92QspQXQtcatcIL3bu3Mxt0co+qiUl7ozfLcnAbG3YBxNAbn00voaxkFXgQm4Pu4g9/+VXfAQ3CnoLYqrfcVoUjHbFa8GNl+jhlaFcgVmZIql3rt2Z96lMW6URmbND0ccbNO28KpjPoHsNzVcIizsF0xH5X2AcbmIZH/tyHRF1kJk1J7MfdLRBKx/Nt4Kk0lNn0valEAjsm67HX7tM4I42MWWe125T3v/7PAb+ZopbWquSeSscyRhAKelwTEhmP/DxlIPoQcBV3OQLrCV0GVSwoVsQYucpCINxXCMUn8dFZ5cYj96a3PvIm7JqMUII4YcTS8XmLegDjQXN7s05rqRflTfXw6S9LYEbsZgquEwC56jHGiv9V19DhLzXrEMTx7uu9uCvcGHgcD8rPFZmXlxUcoXjMIGAKOBtLXLid3deH0OfhEsUaPZtj1Nj+Hbnmg54U32lVpyzfQVO55SsSN7WVlQYAaLv9n13s5zJpJOU2vTKlvAgJKqFFLj1r6YKyAHFWbUf7vViiSnnQ1O4I+HhjbTc/5oPcTs3vY/lrghbAssLeHaKCmlua78HndU4rRgTTvOPQ/ZRKwYi3Gkjv48FteDC0GP4si1fi5A2LvBaEgRHeiD9i6dtZ0uNos83KYdNJZXVsTbblLZcqh42niZ1GOck=
