language: scala
services:
- docker
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
branches:
  only:
  - master
  - "/^v[\\d\\.]+$/"
script: make build
deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^v.*"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - SPARK_VERSION=2.4.5
  - HADOOP_VERSION=2.9.2
  - HIVE_VERSION=2.3.3
  - secure: ZmYmynCM5Wbwpnsly3mDb86ynBvip+ll4nFbR8eNsD26EPtDLpG4T3Ye/EWZUEEZAwlm4ubstc936Hft8FOkGVkNW5gbUY+cnaBOIgTeMr+jrCyo+37LcGLG57t2K1HcuoQdwnetrBV6JPL1fkBttKMZyFWWo60CfZZzxaDtAzaZxH9OfPnDCgqjopc+YIvN9niLZMgZQCQaZ2voMPN0iMPr42RO7ET6xaV08SPZWKtViDSU0MKqedQubWLuQVz15M1lLcZ6s1OVzMxpIHmbnYHhJOKtzdZT3rzt/4ee1uHA5h7XpKQWmaJFObKbRhLFOUj215mFxAcw7qDiUA2Fhgn5N2uQm/nWKY/zqovzOqfy1o1tPelC0kvx7SeRU3zz5c0IqWFUlfEB5eX0SoV8bb6ZEX92C26UoDmF75QtXG79L3DJkjGKUym3JHlcDnbrfXaHXu2bf88ylHNETlTEU4qbwNp0P9A10Ubk7xuu7QgIIbfX8mgyJPHu5pnYFtQzFsgWtsTHyfWv524ZNFzpprEyWPaIdDyvMUJ558m5y/aQIvn9ALv8L/0Q0CrVzd4pQZJJmq1HvWapJz0v7uI50K0/NHtp6jhbTqNZPvkka8Sb+/oFtb4htC8fVYCsITJmrnKVZkETInLuIKV4hAQoSFK4qZkRg7Gv3b8U4CpXSTs=
  - secure: bmNHlmOI9il/6lHoJtA/ELwY0vChnVc0Pg1hJoXQHfORUKh78Lu34WYCOKwTZl31iltPOg9KORkxyDWQQV6dsnYzzNW10KkgXV2blub0aeVEaFbFggMAoRl91vTsdioWh0QbN1OnXjBeswC3kKXjRr/Csyk/NO5Hnqs8lB/EvYHXLVGOUjASE8rX3X4/G1lt6BEJxkpb1klFVS7r0hDNVyNcQ1hbvzqi5/nSQchJP2nRmkDB3IhlsYivExsPkk3hD2Kl0OMSxVRpP4cVxnwffe7HBG7o64u3G9eJyywZ3tdDf/LWMvIdNwlMMgNCsxn5f9SmCQZOU/IaL4F10TyeWyMOE+xB9XVjcXffPXOLXWB6zgzaCEcSyZzPPer8Jw5VpB77znJZyg6iPHY439jMNI2othTgXnNTKRmDUZLje4ehBUGyMeagrht/pQRIwBxYyzt864we3118jzV2ENcU0b/B/WPWK9NU1o6/b/OZyzpCRqj+lqgyn6Bu4tmn5W2u/0knQ8xaUFoMnhJq/kuvoSV5pi2d9odN6+gsFg/tOQwId7RyHFvMdbqJB1wYpnlne7SWvp6E5olxv0g73gJ4NfHSSpL8MDk2QHdpawytun8zFVLriP8I9j6tciO71rnOl50JCVm861T2QswxcSvAcxbpvfAeF2ZfsKj3J8d9+bE=
  - secure: BRkpbABYQmjb0ObyxpcN3nf40h/EbfPqKlg7sWuU4ee9xYkPFAWR6A2T/nOn8EgZdFmfrHsPn6JUDvlqaZKZAxXT7K6eKdywMzbF7WOWyvLyeRE6NriSzeRy5JeZnE9cVO3HG3IEV3xxF6se82hv7uTlxST9cm8RHJjPlKiYcwZt66nkuhTkkfug2dvbA9X2Db/4CE3LyoQEXsWL+sBxTcydcIa3A1rjOoseB5pAY0+lCu1u5GHixUQoEYFCPR0jd0sDTLve3UF0Ryv23IKsaSpL1Q7tG8m/2P8kS31l85dcXVfBrA/gWC+31JTma60gF0+e+flGbVFBKRn6g+frjrsX4olg7qEBTEeyLw3n54FtDNhyYEsNmgfmJ2ayC/LWp/gArRiC4N4PpsxEKm5TaVvcPL1tgqrFqronrEwkk//rPDFxiCSKnFIqfCesnjRMytRv2l72+WACCXlNxXHJv3dwnWbmoGJ4uEBQgnJJKyDI8nrXI21ZnbUdlyVKc5hwe9umgohzLsCtnbyobR50FgA6/ArP7rHYmJudBf8MdufKVueq9PnF9itmpaepU22R9qQBhoQdLOiOorm+Hi+xfLf4empC9phSewtqoXvytdp9kdVntZce8gYKAzDkJbyu+vj3p5Tcnz6vHjjfv0vYAdq9muBDVGjONPfYoBsrlCc=
  - secure: clan5JlxceatqDRRwfkekgVVFjjBpT93w+QPhttRNqsVik6xcJIPZJGghc1SChfS5g5JsCVT/mLwvzyf2sPMD3JHH/jiBdZT6SOVBJ+/rrPmcjE9XF/fMIdqJ0mtR4lJ36C8yxmzOLyO7YkhVw+OHWkeVVv6mFKS2jmGWqphfaU52AVrNAu4UrpGA2n7I+Aqz8kp4VgNmsq3BJRM2FbLMGctv7i1WMNcDVW1x7ry2XGOZ1f1hnxWL8dwo+E4eAvC4YcbWHrxpQmQL+W2znEghwblg544A37kKOlxbdMFIP4DJW/FoznPAYfqSFZRmQ78VJYzzkVwYq+GrMJrFWslJQd023q1SKeNVvpJ4rr/xCjmFriom/GtbTl61Ts7Ddfbp3Ihh5uw7dpDo1IBBlZO8daVZuhI16kHpLZtvTZ2VRU1DTwRB/dCtVIVQCu7vaOU8HQ7SncGa7wzpa9pRrn/IRxfpHNSQvM+Qyq9zL8+9zetagkC4tyBSF4ds1yfvhtXw2dEOECNwty6dJCHuM/P2nURIMY70yg875g4iEZEgmWLFBzZhIh7eNIdPQPnoukSQ1Iotz7RLWcLoTaE72GDG9rF+VBiMZu7I63lEA7SjRuRD+B4AVL+rvvYMjtPQulZm/XUlHQpko8Gh0moQ+4Zv/Np1AqWxKx9TCEc3dtBEFo=
  - secure: el/meQMYrqEr0ouVdF3r7y8CyqyG1gonU/kAo5315zlnnaCnxslqxdNzkcUcyyTq2p0EFaE2YoxesPmAV+PK7z9/Pd96HmAVK3/NV+VScf7KECDhr9GImOz6+V8TmmGcVxg54CKTwn6YP3+A4nB0VEA3rZu5KKlmbbUj5gIgBRQqwSvX+wpK+nHe3ITPgDBiywWn/QMlRHZEHXGpxlKMpAQyQ4iGGEKA1h3a9Hs1mZ9j9kKEHOBNcMu3vBxYR7Q8hJwt1MnaKBZO0ce+LSscGKMFFwD3MAVNF7Ni7+F+HZSom/ifHeV4Uly7vwgKnOcSVsXBgns+Me3hdcTnWVLxiMc71wabW5UZIgdPa+EN5kf6QT9WWLqfNTXasHLaq4z/5sOK3NDtImc5RAGwsievLtzPNk/Mf7U+pe2mEbqqffC4/qYQa9dfL2FJxG6+E5Inv1blIY0xxotwtyS8GgnPA6F3hZpP4rDI5UFgjfu+pykzw7DP7rFABxIxHcTe8QNrqaD8L2wkeONhCvoDNljr/I+SDnPI7P28Kqt3rVkcJT5Y8p36a98fRnLQ/h0hHsWAO8TH0eB1LHO6Qou64G78XBF26/fiW50QglvCxeFeqn42c71kbZNTFD1hVjKp4ZC+tFUHzW8E0PnKoXaNBq9QoSaSBIshFwK5sodz4HLjd94=
before_install:
- openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in .travis/pubring.gpg.enc -out .travis/pubring.gpg  -d
- openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in .travis/secring.gpg.enc -out .travis/secring.gpg  -d
- chmod +x e2e/**/*.sh
