language: scala
services:
  - docker
os: linux
dist: bionic
jdk:
  - openjdk8
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
branches:
  only:
    - master
    - /^v[\d\.]+$/
# SONATYPE_USERNAME SONATYPE_PASSWORD GPG_KEY_NAME GPG_PASSPHRASE ENCRYPTION_PASSWORD CODECOV_TOKEN
env:
  global:
    - SPARK_VERSION=2.4.5
    - HADOOP_VERSION=2.9.2
    - HIVE_VERSION=2.3.3
    - secure: FFH+YYcVKX1ebbu3J1bKYQwxEfGTBLPxsx3htQyow/ui4ROjwrMHd7i2ooy0PdtV68yGWHDhDrL2EkdekiHoYsvlMfLq0cbCtHWhIZcbFX9kcd6mZeV1ua5zFYyx+Qh0t8+056KvKwOK5Klp9CUp9Fpky9hGhElRphh84XZYQdkda9bGI2UZdyKOlAgivwN9Shs5Vb1XDu7ITIHC3E1McqGeeMOXlBvdSoD8zSNPxDKioOI33GGJFALNsr9jNb8M1cgAIpqGSgl0AAJgE78VZG2Z7mHjKJwDVPs/3awkjQoY0XKLs9qG/jV0cfSOG6YEEThCH3sZxD8jRZNC2m16Cr6sr2RJt1DQTGJpNmAzCiu3JFxaQRFxFXYitCZPEp6dB2lTYqYQ+em+Um7Q554Y8B29q+Owy336tLg5QzO48pdbnxtCXBVjeQ1sZqHch4zsjXZQr8Pk88KRU22cfsWe8M5wVZbb3SaWb2EW8J7UVQLE9tOlDa1Z3PMfnR4YcJQ33BsZS8e9GGo5ZgJp2J9ijuC1BbBQ3Wc6dOjQdQo4Zpg01jjW4XSpMaeJpWdzeafoWyyToTS1y/XybTyepy0B1GAOLshZKW6AmTut0HEWDRSgo89SzArgakMy1scuAtGQhXEk4pMEIUJx6wTlS7T+qurMyFW2Rdc8B5WsuKJmwjw=
    - secure: D9ENseheYQ7DDWRveKeH5/ToBIHdS5VU5EAx2LTX5yqu1LO602+XF+rHGcLNfnYGvRUbX2WYIC5BrxdNtoIyBWwdSvJ+zy8C4JT0LcvFGlh2XMSZo84CvfkJxkCMSsikEDn62gagnDn+4VVkvxsvqq1XSfPNoAYf8N6+t8ccowb1h7Ojw0zxEE8oASdBc/tSqzRpiRjxv+cGTYUiES7W47/jci+NCroxtoq/bM7lhvs8FevJE2KPQgzZCkJDc8MoFpbr7ALOYotahRRn76AP4EXv+KGilK15XktbsMFOVgyQAEpfohAxf5CTWYtam8GrEnWWjKl3hkotggZB2wyAepGABZAZRhj30izfQz89H0XkSBwLyMWNl6JmCiHJ2Syfi5Qi23cxKMgTWcSdluXkSi0p4rSCro015452oJO+X5SaukYIXPiczf8dhanwES+ReT4f0B2L8Ay9E+rgvTFgm8pdQXMkxzpbec/MUgzKMRFWRSunySjZEKE1LJ13DfhZgw1t+M60XWQ976Tg+ItXXxcYWxeDJ19m2X2sDUjILGqwK/O4sfKpDTofhe8I6A2n/3SuggSRtom2Au0rCOk5cevhu4VchDdmNj8maXQMvCTRsbS1W8v7mJ8wlwMuEB83nKS9LlIWvUE8cu2gSc2MKWVXT00gzG/X9h9XNxTZ1is=
    - secure: Xnt2rsF+IJCMdwSYrQ1FlKXm+p+5097Oh9BDofDBlIrUDk1xRJjFKyiP+Enj9TyL9E2hX9ERJCyItkxwKeGvUZyZ9n36u93oj/m/uodxDFzMoOdf5mtAVCKdwSyUic/kZlGMkRa3MMgxqJAa3RiIZAvz4PnXjhZFq7M6sg/nj2V1SnngHQl8PjMC039tcDCuVKpcr8i0mMZ/Idh/BW11XBFR19cs6BZFceQu6fnPalnr64Rjxw1gQNSczAmS6CT3XQKCxiOKtkSPkvUqOhm+JIZPv0fAUOfTzLFGy5K8EmJKHywPcnl2MpT1B+9R6BtIRdbOm2N1CyB3oC6wcFslhSQHrJ3h5CO19XTFJ26J/tUsTQ7yI9pkVPnRVk+ejV1DogWzZNJXM8+e9TNSx9oYqIDFQbIL0SNjSlR3OsBcrEsT6Xx9OW+pHMJQMgHm8KX3z4K2pRGZtNR9TR/EUdNTgUVm3N6nB/IBAKPDPwTQwXscE+wuB8x8kjAqK3mzuDxdUsm0Kp1+44uKLf3pn9BHYieMYlLyqeX9OQEjDdVRXkGTkNiefHz2ktgPLYm7ILZoet/GPQWZkhSCTODcpoylKZ9eILKNYyCWILTo25UvbCP0a+ZRSkQnbndIBbTL3Pn6HaNae/LMa/Nedyra+mKgLBIswvNzveFiK2EL0EaX+e4=
    - secure: KKxhC0Mtxys+zt5W8/86OtioQcZNaHSlNgj8R4KDWoQLoBpLygU9XQmqa9YF2rV6+6SZ1/ZjlAyfNL8km0NidH2XCZQT+fiiZVptlRH3CsQrqvg1s3R+XKIfXjtCZTP32e1S5RPcCKR5uSVP6adKp+E9wbWyc/Hm+HG6l6HpE1bAfzV51QEECV5FFaHnBhXjX/ORvWBsIe5JgfMb7UyWj5ybiHyisghwk7jhrpYoW1ZQP09ku2Q2fDXofdxuA/RK/Qou2XVoKxvQGuzgAu7NPGNZk5JBVBaCsWg3SGq9w17J0JIqe5ZLkmeuFv+igovplU8TvZJlQgpkg/b/JT8FmVkoBmBkh6O7fHqNUlvcGaJyLblH2rYCjXvxJtdG2AEBIBdpYBrwE4nnrUCEfUy2xjQzD9pRMZxw7lhWT6NBcrMnDekXvGkwIv7+pW0QGpb1wrKuvdC/CLSmtDRoRl5JQ7q+18/QVF/Ig/aRrSfeVJyICq08Hgk7XZjs8wvSFmZUp+gDExZ0dHL7jaU1sYq0oUWXWzrgVPutsXrm3yAxFAOW26cZcAH2mfa2tWlGDq/fRNxh+Iml7Ts+s7734WLVXWZm+/NXvN14sCdOrRFux9rwxweCZvr8gzoC7/2U2/pnOvG5mBca7ccekaltP46M9Oh4L8OuVEY/ivCliGulTtM=
    - secure: Ji9ndh8KYevNWclQR0zYWTJoJpTwySi5oH7Izb8dN94Kju34GsljXO8+2SkwUOzxMJ4BZdh5BshSvYpFfE4391nrvUEN+zfj9oLQvebvBl+boSODZxphJjRwi3qaraoZ40fyfWJN/Gjdt2+dPCO3tA9QEubdwfH1zmkqEIQCkf31hfcJydpepyYCgKZhkOECFcrOakoRdKu/TLWGivryKf8AfOahunlt6Z+Rzcg4GwlvwhAFgwCUXRFtqeNfYxDV4utPuAvJuM9Bdbj1DVM5EAAxgKee7G6n5+ZyijHYBY0Dp96xtc2X/tW8i5jz4NXsyRhrWqRMI5mUTYQh97LR6BBLBRRg4ZhWT4suXFKwiixXKj5JaNKNHLk90aetUhkM2fFLqmUlxBQqFUTetDxuS3fMMqaBmL/xNJxTz9wIOkSZJtaHzHfSRx6rcpp6JQAdCktNbQVy3Y+ySicCYXngeuHAXMB428BfWqLm07e5sDjxPQUOcalQDkUmsyw0RelhrOP3du9ip+vwikZusVz/fBmTcK6gAvKVBLPnyLDgYVC1lswJBcgbAyvRBSM5dT+SIanmHLIjICmpQK0zKnK0g2RfrsCVNVQtDFR634Ijk1Ctz7LtxKxLacsUIarRiT2J536I70d1y3AVZTBtTKKJO6iAKXShUxJz7GcQLEngtUg=
    - secure: V0a/KdPtT302rsg7MFcjhZrpyhKSWfueeWKHmG6Ltrnq4JydQnxFS4jB12SdDX/Q5D4Rdp92tNuCi95gqk2ANLbHc64v/XageiyW8HrPP8PH8qfKYDs/LsB16neNpoxkJSwRer3YfALOKYVyyyBnUz0ir1BxBEC3Wvpbp8HaaNMaS+rgoab/AbRfzDfof0iFn46W5yfSFemh830I9JSRr1dU2B/51XKE4Yxw/ewIZkuzsomNVv3EVrQYg1FVH3SUV3955HwPWYNTjeuoyfZpHifv6mmWXQ/5Bmd6ZXtqsvAwAaRrI/lFWnTrU7UcCNDAjGJGr137lhSirx2BVGRRa6WCtnWYHpwYLopy9247bW9eQ0z0M3H5o2QxwHyBhKNGEgANDxBnF9KBuMO/2STKU1vCNUnDq4qOM8YZ/GttPeIOAxy3X3WDHNK3FsXYpb9xYEO+Sl9epAiIBrnUG64jZExbROvME12OT78F0v/kqi8C2VAypL4ah8L+flxGOo5S+gEywDs2H+prhfAHBAtBNGGgDe2E9RQB4TqcfnZ0QqUxUWyUBG+jyMBFqOwTjnG6AKr2nOsCyoNW9tH5Q0vp/kpKUVdJ8FXxMEKlWRJjUnNov24oZUN+UFR9LehL7RYM/Bilfj+16VGOpIAOu6O2/RpYhryOBhzO86u4kguq6rs=
before_install:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis/pubring.gpg.enc -out .travis/pubring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis/secring.gpg.enc -out .travis/secring.gpg -d
jobs:
  include:
    - stage: build
      script: .travis/scripts/build.sh
    - stage: test
      before_script: .travis/scripts/docker.sh
      script: .travis/scripts/test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      deploy:
        provider: script
        script: .travis/scripts/deploy.sh
        skip_cleanup: true
        on:
          tags: true