version: '3'
services:
  spark-master:
    image: qiniu/stream-spark
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WEBUI_PORT=8080
    entrypoint:
      - /scripts/entrypoint-master.sh
  spark-worker-1:
    image: qiniu/stream-spark
    container_name: spark-worker-1
    ports:
      - "7078:7078"
      - "8081:8081"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_PORT=7078
      - SPARK_WORKER_WEBUI_PORT=8081
    entrypoint:
      - /scripts/entrypoint-worker.sh
  spark-worker-2:
    image: qiniu/stream-spark
    container_name: spark-worker-2
    ports:
      - "7079:7079"
      - "8082:8082"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_PORT=7079
      - SPARK_WORKER_WEBUI_PORT=8082
    entrypoint:
      - /scripts/entrypoint-worker.sh
  spark-submit:
    image: qiniu/stream-spark
    container_name: spark-submit
    ports:
      - "4040:4040"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_UI_PORT=4040
      - MIN_WORKERS=2
      - MAX_RETRIES=300
      - SUBMIT_COMMAND=spark-submit --class com.qiniu.stream.core.PipelineRunner stream-standlone -c examples/movies.yaml
    entrypoint:
      - /scripts/entrypoint-submit.sh